[[main]]
  identifier = ""
  name = "首页"
  url = ""
  weight = 1

[[main]]
  identifier = "archive"
  name = "存档"
  url = "archive"
  weight = 2

[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 3

# [[main]]
#   identifier = "posts"
#   name = "博文"
#   url = "posts"
#   weight = 1

# [[main]]
#   identifier = "gallery"
#   name = "相册"
#   url = "gallery"
#   weight = 3

# [[main]]
#   parent = "gallery"
#   name = "Cartoon"
#   url = "gallery/cartoon"

# [[main]]
#   parent = "gallery"
#   name = "Photo"
#   url = "gallery/photo"

# [[main]]
#   identifier = "publication"
#   name = "发表"
#   url = "publication"
#   weight = 7

# [[main]]
#   identifier = "presentation"
#   name = "演示"
#   url = "presentation"
#   weight = 3

# [[main]]
#   identifier = "showcase"
#   name = "项目"
#   url = "showcase"
#   weight = 3